-- =============================================
-- MAIN QUESTS — Progressive coding challenges
-- =============================================

-- Easy Main Quests
INSERT INTO quests (title, description, difficulty, xp_reward, skill_reward, quest_type) VALUES
('The First Gate', E'Write a function that returns the sum of all numbers in an array.\n\n---EXAMPLES---\nInput: [1, 2, 3, 4]\nOutput: 10\n\nInput: [-1, 5, 3]\nOutput: 7\n\n---STARTER---\nfunction sumAll(arr) {\n  // Your code here\n}\n\nconsole.log(sumAll([1, 2, 3, 4]));\nconsole.log(sumAll([-1, 5, 3]));', 'easy', 25, 1, 'main'),

('Shadow Extract: Fibonacci', E'Generate the first N numbers of the Fibonacci sequence.\n\n---EXAMPLES---\nInput: 6\nOutput: [0, 1, 1, 2, 3, 5]\n\nInput: 3\nOutput: [0, 1, 1]\n\n---STARTER---\nfunction fibonacci(n) {\n  // Your code here\n}\n\nconsole.log(fibonacci(6));\nconsole.log(fibonacci(3));', 'easy', 25, 1, 'main'),

('Hunter''s Toolkit: String Counter', E'Count the frequency of each character in a string. Return an object with character counts.\n\n---EXAMPLES---\nInput: "hello"\nOutput: { h: 1, e: 1, l: 2, o: 1 }\n\nInput: "aab"\nOutput: { a: 2, b: 1 }\n\n---STARTER---\nfunction charCount(str) {\n  // Your code here\n}\n\nconsole.log(charCount("hello"));\nconsole.log(charCount("aab"));', 'easy', 20, 1, 'main'),

('Awakening: Remove Duplicates', E'Remove duplicate values from an array while preserving the original order.\n\n---EXAMPLES---\nInput: [1, 2, 2, 3, 4, 4, 5]\nOutput: [1, 2, 3, 4, 5]\n\nInput: ["a", "b", "a", "c"]\nOutput: ["a", "b", "c"]\n\n---STARTER---\nfunction removeDuplicates(arr) {\n  // Your code here\n}\n\nconsole.log(removeDuplicates([1, 2, 2, 3, 4, 4, 5]));', 'easy', 20, 1, 'main');

-- Medium Main Quests
INSERT INTO quests (title, description, difficulty, xp_reward, skill_reward, quest_type) VALUES
('Dungeon Crawler: Linked List', E'Implement a singly linked list with insert, delete, and search operations.\n\n---EXAMPLES---\nlist.insert(1) → list.insert(2) → list.insert(3)\nlist.search(2) → true\nlist.delete(2)\nlist.search(2) → false\nlist.toArray() → [1, 3]\n\n---STARTER---\nclass Node {\n  constructor(val) {\n    this.val = val;\n    this.next = null;\n  }\n}\n\nclass LinkedList {\n  constructor() {\n    this.head = null;\n  }\n\n  insert(val) {\n    // Add to end\n  }\n\n  delete(val) {\n    // Remove first occurrence\n  }\n\n  search(val) {\n    // Return true/false\n  }\n\n  toArray() {\n    // Return array of values\n  }\n}\n\nconst list = new LinkedList();\nlist.insert(1);\nlist.insert(2);\nlist.insert(3);\nconsole.log(list.search(2)); // true\nlist.delete(2);\nconsole.log(list.toArray()); // [1, 3]', 'medium', 45, 2, 'main'),

('Raid Boss Prep: Stack Calculator', E'Build a calculator that evaluates postfix (Reverse Polish Notation) expressions using a stack.\n\n---EXAMPLES---\nInput: "3 4 + 2 *"\nOutput: 14\n\nInput: "5 1 2 + 4 * + 3 -"\nOutput: 14\n\n---STARTER---\nfunction evalPostfix(expression) {\n  const stack = [];\n  // Your code here\n}\n\nconsole.log(evalPostfix("3 4 + 2 *")); // 14\nconsole.log(evalPostfix("5 1 2 + 4 * + 3 -")); // 14', 'medium', 50, 2, 'main'),

('Shadow Army: Sorting Algorithms', E'Implement both Merge Sort and Quick Sort. Compare their behavior on the same input.\n\n---EXAMPLES---\nInput: [38, 27, 43, 3, 9, 82, 10]\nOutput: [3, 9, 10, 27, 38, 43, 82]\n\n---STARTER---\nfunction mergeSort(arr) {\n  // Implement merge sort\n}\n\nfunction quickSort(arr) {\n  // Implement quick sort\n}\n\nconst arr = [38, 27, 43, 3, 9, 82, 10];\nconsole.log("Merge:", mergeSort([...arr]));\nconsole.log("Quick:", quickSort([...arr]));', 'medium', 50, 2, 'main'),

('The Red Gate: Hash Map', E'Implement a basic hash map from scratch with put, get, and remove operations. Handle collisions with chaining.\n\n---EXAMPLES---\nmap.put("name", "Sung Jin-Woo") → map.get("name") → "Sung Jin-Woo"\nmap.put("rank", "S") → map.get("rank") → "S"\nmap.remove("rank") → map.get("rank") → undefined\n\n---STARTER---\nclass HashMap {\n  constructor(size = 16) {\n    this.buckets = new Array(size).fill(null).map(() => []);\n    this.size = size;\n  }\n\n  _hash(key) {\n    // Simple hash function\n  }\n\n  put(key, value) {\n    // Your code here\n  }\n\n  get(key) {\n    // Your code here\n  }\n\n  remove(key) {\n    // Your code here\n  }\n}\n\nconst map = new HashMap();\nmap.put("name", "Sung Jin-Woo");\nconsole.log(map.get("name")); // Sung Jin-Woo\nmap.remove("name");\nconsole.log(map.get("name")); // undefined', 'medium', 55, 3, 'main');

-- Hard Main Quests
INSERT INTO quests (title, description, difficulty, xp_reward, skill_reward, quest_type) VALUES
('S-Rank Trial: Dynamic Programming', E'Solve the classic Knapsack problem using dynamic programming. Given items with weights and values, find the maximum value that fits in a knapsack of given capacity.\n\n---EXAMPLES---\nInput: items = [{w:1,v:6},{w:2,v:10},{w:3,v:12}], capacity = 5\nOutput: 22 (items 1+3: weight 1+3=4, value 6+12=18... actually 10+12=22 with items 2+3)\n\n---STARTER---\nfunction knapsack(items, capacity) {\n  // Use dynamic programming\n  // items = [{w: weight, v: value}, ...]\n}\n\nconst items = [\n  { w: 1, v: 6 },\n  { w: 2, v: 10 },\n  { w: 3, v: 12 }\n];\nconsole.log(knapsack(items, 5)); // 22', 'hard', 80, 4, 'main'),

('National Level: Graph Algorithms', E'Implement Dijkstra''s shortest path algorithm for a weighted graph. Return the shortest distances from a source node to all other nodes.\n\n---EXAMPLES---\nGraph: { A: [{to:B,w:4},{to:C,w:2}], B: [{to:D,w:3}], C: [{to:B,w:1},{to:D,w:5}], D: [] }\nStart: A\nOutput: { A:0, B:3, C:2, D:6 }\n\n---STARTER---\nfunction dijkstra(graph, start) {\n  // Your code here\n}\n\nconst graph = {\n  A: [{to:"B",w:4},{to:"C",w:2}],\n  B: [{to:"D",w:3}],\n  C: [{to:"B",w:1},{to:"D",w:5}],\n  D: []\n};\nconsole.log(dijkstra(graph, "A"));', 'hard', 80, 4, 'main'),

('Monarch''s Domain: Event Emitter', E'Build a custom EventEmitter class supporting on, off, once, and emit methods.\n\n---EXAMPLES---\nconst emitter = new EventEmitter();\nconst handler = (data) => console.log(data);\nemitter.on("event", handler);\nemitter.emit("event", "hello"); // prints "hello"\nemitter.off("event", handler);\nemitter.emit("event", "world"); // nothing\n\nemitter.once("single", (d) => console.log(d));\nemitter.emit("single", "fire"); // prints "fire"\nemitter.emit("single", "again"); // nothing\n\n---STARTER---\nclass EventEmitter {\n  constructor() {\n    this.events = {};\n  }\n\n  on(event, handler) {\n    // Subscribe\n  }\n\n  off(event, handler) {\n    // Unsubscribe\n  }\n\n  once(event, handler) {\n    // Subscribe for one-time use\n  }\n\n  emit(event, ...args) {\n    // Fire all handlers\n  }\n}\n\nconst emitter = new EventEmitter();\nemitter.on("test", (msg) => console.log(msg));\nemitter.emit("test", "Hello!"); // Hello!\nemitter.once("once", (msg) => console.log(msg));\nemitter.emit("once", "First"); // First\nemitter.emit("once", "Second"); // nothing', 'hard', 75, 4, 'main'),

('Shadow Sovereign: Trie', E'Implement a Trie (prefix tree) with insert, search, and startsWith operations.\n\n---EXAMPLES---\ntrie.insert("apple")\ntrie.search("apple")   → true\ntrie.search("app")     → false\ntrie.startsWith("app") → true\ntrie.insert("app")\ntrie.search("app")     → true\n\n---STARTER---\nclass TrieNode {\n  constructor() {\n    this.children = {};\n    this.isEnd = false;\n  }\n}\n\nclass Trie {\n  constructor() {\n    this.root = new TrieNode();\n  }\n\n  insert(word) {\n    // Your code here\n  }\n\n  search(word) {\n    // Return true if exact word exists\n  }\n\n  startsWith(prefix) {\n    // Return true if any word starts with prefix\n  }\n}\n\nconst trie = new Trie();\ntrie.insert("apple");\nconsole.log(trie.search("apple"));    // true\nconsole.log(trie.search("app"));      // false\nconsole.log(trie.startsWith("app"));  // true', 'hard', 75, 4, 'main');


-- =============================================
-- BOSS QUESTS — Epic multi-part challenges
-- =============================================

INSERT INTO quests (title, description, difficulty, xp_reward, skill_reward, quest_type) VALUES
('💀 Igris the Bloodred', E'Defeat Igris by implementing a complete Mini Database engine. Support INSERT, SELECT (with WHERE), and DELETE operations on in-memory tables.\n\n---EXAMPLES---\ndb.execute("CREATE TABLE hunters (name, rank, level)")\ndb.execute("INSERT INTO hunters VALUES (''Jin-Woo'', ''S'', 100)")\ndb.execute("INSERT INTO hunters VALUES (''Cha'', ''S'', 95)")\ndb.execute("SELECT * FROM hunters WHERE rank = ''S''") → [{name:"Jin-Woo",rank:"S",level:"100"},{name:"Cha",rank:"S",level:"95"}]\ndb.execute("DELETE FROM hunters WHERE name = ''Cha''")\n\n---STARTER---\nclass MiniDB {\n  constructor() {\n    this.tables = {};\n  }\n\n  execute(sql) {\n    // Parse and execute SQL-like commands\n    // Support: CREATE TABLE, INSERT INTO, SELECT * WHERE, DELETE WHERE\n  }\n}\n\nconst db = new MiniDB();\ndb.execute("CREATE TABLE hunters (name, rank, level)");\ndb.execute("INSERT INTO hunters VALUES (''Jin-Woo'', ''S'', 100)");\ndb.execute("INSERT INTO hunters VALUES (''Cha'', ''S'', 95)");\nconsole.log(db.execute("SELECT * FROM hunters WHERE rank = ''S''"));\ndb.execute("DELETE FROM hunters WHERE name = ''Jin-Woo''");\nconsole.log(db.execute("SELECT * FROM hunters"));', 'hard', 150, 5, 'boss'),

('💀 Tusk the Ice Elf', E'Defeat Tusk by implementing a Promise-based task scheduler. The scheduler should execute async tasks with a concurrency limit, supporting priority queues and retry logic.\n\n---EXAMPLES---\nconst scheduler = new TaskScheduler(2); // max 2 concurrent\nscheduler.add(() => delay(100).then(() => "A"), { priority: 1 });\nscheduler.add(() => delay(50).then(() => "B"), { priority: 2 });\nscheduler.add(() => delay(200).then(() => "C"), { priority: 1, retries: 2 });\nawait scheduler.run(); // Executes B first (higher priority), max 2 at a time\n\n---STARTER---\nfunction delay(ms) {\n  return new Promise(r => setTimeout(r, ms));\n}\n\nclass TaskScheduler {\n  constructor(concurrency = 2) {\n    this.concurrency = concurrency;\n    this.queue = [];\n    this.running = 0;\n    this.results = [];\n  }\n\n  add(taskFn, options = {}) {\n    // Add task with priority and retry options\n  }\n\n  async run() {\n    // Execute all tasks respecting concurrency limit\n  }\n}\n\nconst scheduler = new TaskScheduler(2);\nscheduler.add(() => delay(100).then(() => "Task A"));\nscheduler.add(() => delay(50).then(() => "Task B"));\nscheduler.add(() => delay(200).then(() => "Task C"));\nscheduler.run().then(results => console.log(results));', 'hard', 150, 5, 'boss'),

('💀 Baran the White Flame', E'Build a complete state machine that can model complex workflows. Implement states, transitions, guards, and actions.\n\n---EXAMPLES---\nconst machine = new StateMachine({\n  initial: "idle",\n  states: {\n    idle: { on: { START: "running" } },\n    running: { on: { PAUSE: "paused", FINISH: "done" } },\n    paused: { on: { RESUME: "running", CANCEL: "idle" } },\n    done: { type: "final" }\n  }\n});\n\nmachine.state → "idle"\nmachine.send("START") → "running"\nmachine.send("PAUSE") → "paused"\nmachine.send("RESUME") → "running"\nmachine.send("FINISH") → "done"\nmachine.send("START") → "done" (final, no transition)\n\n---STARTER---\nclass StateMachine {\n  constructor(config) {\n    this.config = config;\n    this.state = config.initial;\n    this.history = [config.initial];\n  }\n\n  send(event) {\n    // Transition to next state if valid\n    // Return current state\n  }\n\n  canTransition(event) {\n    // Check if transition is possible\n  }\n\n  getHistory() {\n    return this.history;\n  }\n}\n\nconst machine = new StateMachine({\n  initial: "idle",\n  states: {\n    idle: { on: { START: "running" } },\n    running: { on: { PAUSE: "paused", FINISH: "done" } },\n    paused: { on: { RESUME: "running", CANCEL: "idle" } },\n    done: { type: "final" }\n  }\n});\n\nconsole.log(machine.state); // idle\nconsole.log(machine.send("START")); // running\nconsole.log(machine.send("PAUSE")); // paused\nconsole.log(machine.send("RESUME")); // running\nconsole.log(machine.send("FINISH")); // done', 'hard', 150, 5, 'boss'),

('💀 The Architect', E'The ultimate boss. Build a reactive data binding system — like a mini Vue/React reactivity engine. Objects become reactive: when properties change, dependent computed values auto-update.\n\n---EXAMPLES---\nconst state = reactive({ price: 10, quantity: 5 });\nconst total = computed(() => state.price * state.quantity);\nconsole.log(total.value); // 50\nstate.price = 20;\nconsole.log(total.value); // 100\nstate.quantity = 3;\nconsole.log(total.value); // 60\n\n---STARTER---\nlet activeEffect = null;\n\nfunction reactive(target) {\n  // Return a proxy that tracks property access and triggers updates\n}\n\nfunction computed(fn) {\n  // Return an object with a .value that auto-recomputes when dependencies change\n}\n\nfunction effect(fn) {\n  // Run fn and track its dependencies\n}\n\n// Test\nconst state = reactive({ price: 10, quantity: 5 });\nconst total = computed(() => state.price * state.quantity);\nconsole.log(total.value); // 50\nstate.price = 20;\nconsole.log(total.value); // 100\nstate.quantity = 3;\nconsole.log(total.value); // 60', 'hard', 200, 8, 'boss');


-- =============================================
-- SPECIAL QUESTS — Unique themed challenges
-- =============================================

INSERT INTO quests (title, description, difficulty, xp_reward, skill_reward, quest_type) VALUES
('🌟 Hunter Exam: Decode the Message', E'A secret message has been encoded. Each letter is shifted by a key (Caesar cipher). Write functions to encode and decode messages with any shift key.\n\n---EXAMPLES---\nencode("HELLO", 3) → "KHOOR"\ndecode("KHOOR", 3) → "HELLO"\nencode("Attack at dawn", 5) → "Fyyfhp fy ifbs"\n\n---STARTER---\nfunction encode(message, key) {\n  // Shift each letter by key positions\n}\n\nfunction decode(message, key) {\n  // Reverse the shift\n}\n\nconsole.log(encode("HELLO", 3)); // KHOOR\nconsole.log(decode("KHOOR", 3)); // HELLO\nconsole.log(encode("Attack at dawn", 5));', 'easy', 30, 2, 'special'),

('🌟 Dungeon Map Generator', E'Generate a random dungeon map as a 2D grid. Place rooms (R), corridors (.), walls (#), and an entrance (E) and exit (X). Ensure there is always a valid path from E to X.\n\n---EXAMPLES---\nInput: generateDungeon(8, 8)\nOutput:\n########\n#E..#..#\n#.#...R#\n#.###..#\n#R....R#\n#.##.#.#\n#....#X#\n########\n\n---STARTER---\nfunction generateDungeon(width, height) {\n  // Create a 2D grid\n  // Place walls, rooms, corridors\n  // Ensure path from E to X exists\n  // Return the grid as a string\n}\n\nfunction hasPath(grid, start, end) {\n  // BFS/DFS to verify path exists\n}\n\nconsole.log(generateDungeon(8, 8));', 'medium', 50, 3, 'special'),

('🌟 System Window: JSON Parser', E'Build a JSON parser from scratch. Parse a JSON string into a JavaScript value WITHOUT using JSON.parse().\n\n---EXAMPLES---\nmyParse(''{"name":"Jin-Woo","level":100}'') → { name: "Jin-Woo", level: 100 }\nmyParse(''[1, "two", true, null]'') → [1, "two", true, null]\nmyParse(''"hello"'') → "hello"\nmyParse(''42'') → 42\n\n---STARTER---\nfunction myParse(jsonStr) {\n  let pos = 0;\n\n  function parseValue() {\n    skipWhitespace();\n    // Determine type and parse accordingly\n  }\n\n  function parseString() {\n    // Parse "..." string\n  }\n\n  function parseNumber() {\n    // Parse number\n  }\n\n  function parseObject() {\n    // Parse { key: value, ... }\n  }\n\n  function parseArray() {\n    // Parse [ value, ... ]\n  }\n\n  function skipWhitespace() {\n    while (pos < jsonStr.length && " \\t\\n\\r".includes(jsonStr[pos])) pos++;\n  }\n\n  return parseValue();\n}\n\nconsole.log(myParse(''{"name":"Jin-Woo","level":100}''));\nconsole.log(myParse(''[1,"two",true,null]''));', 'hard', 70, 4, 'special'),

('🌟 Shadow Exchange: Rate Limiter', E'Implement a rate limiter using the Token Bucket algorithm. It should allow burst traffic up to a limit and refill tokens at a steady rate.\n\n---EXAMPLES---\nconst limiter = new RateLimiter({ maxTokens: 5, refillRate: 1, refillInterval: 1000 });\nlimiter.tryAcquire() → true  (4 tokens left)\nlimiter.tryAcquire() → true  (3 tokens left)\n// ... exhaust all 5\nlimiter.tryAcquire() → false (rate limited)\n// After 1 second, 1 token refilled\nlimiter.tryAcquire() → true\n\n---STARTER---\nclass RateLimiter {\n  constructor({ maxTokens, refillRate, refillInterval }) {\n    this.maxTokens = maxTokens;\n    this.tokens = maxTokens;\n    this.refillRate = refillRate;\n    this.refillInterval = refillInterval;\n    this.lastRefill = Date.now();\n  }\n\n  tryAcquire() {\n    this._refill();\n    // Check if token available, consume one\n  }\n\n  _refill() {\n    // Add tokens based on elapsed time\n  }\n\n  getTokens() {\n    this._refill();\n    return this.tokens;\n  }\n}\n\nconst limiter = new RateLimiter({ maxTokens: 5, refillRate: 1, refillInterval: 1000 });\nconsole.log(limiter.tryAcquire()); // true\nconsole.log(limiter.tryAcquire()); // true\nconsole.log(limiter.getTokens()); // 3', 'medium', 50, 3, 'special'),

('🌟 Monarch''s Memory: Memoization Engine', E'Build a powerful memoization utility that caches function results. Support TTL (time-to-live), max cache size with LRU eviction, and cache statistics.\n\n---EXAMPLES---\nconst add = memoize((a, b) => a + b, { maxSize: 3, ttl: 5000 });\nadd(1, 2) → 3 (computed)\nadd(1, 2) → 3 (cached)\nadd(3, 4) → 7 (computed)\nadd.stats() → { hits: 1, misses: 2, size: 2 }\n\n---STARTER---\nfunction memoize(fn, options = {}) {\n  const { maxSize = 100, ttl = Infinity } = options;\n  // Your cache implementation here\n\n  function memoized(...args) {\n    // Check cache, compute if needed, manage eviction\n  }\n\n  memoized.stats = () => {\n    // Return { hits, misses, size }\n  };\n\n  memoized.clear = () => {\n    // Clear the cache\n  };\n\n  return memoized;\n}\n\nconst add = memoize((a, b) => a + b, { maxSize: 3 });\nconsole.log(add(1, 2)); // 3 (computed)\nconsole.log(add(1, 2)); // 3 (cached)\nconsole.log(add(3, 4)); // 7 (computed)\nconsole.log(add.stats()); // { hits: 1, misses: 2, size: 2 }', 'medium', 55, 3, 'special'),

('🌟 Arise: Code Transpiler', E'Build a mini code transpiler that converts a simplified pseudo-language into JavaScript. Support variable declarations, if/else, loops, and functions.\n\n---EXAMPLES---\nInput:\n  let x = 10\n  if x > 5 then\n    print "big"\n  else\n    print "small"\n  end\n\nOutput (JS):\n  let x = 10;\n  if (x > 5) {\n    console.log("big");\n  } else {\n    console.log("small");\n  }\n\n---STARTER---\nfunction transpile(pseudoCode) {\n  const lines = pseudoCode.trim().split("\\n");\n  let output = [];\n\n  for (let i = 0; i < lines.length; i++) {\n    const line = lines[i].trim();\n    // Transform each line to valid JavaScript\n  }\n\n  return output.join("\\n");\n}\n\nconst code = `let x = 10\nif x > 5 then\n  print "big"\nelse\n  print "small"\nend`;\n\nconsole.log(transpile(code));', 'hard', 80, 5, 'special');
